### ISSUE TITLE
demo / model_zoo / resnet 

### ISSUE THREAD

**Issue by huangpingchun** [baidu/Paddle#194]
Use official website provides resnet pre-trained model predicted pictures are of the same label
![2016-10-12 14 25 55](https://cloud.githubusercontent.com/assets/12268414/19299643/3610b558-9088-11e6-9328-2a81f4f348ca.png)

**Comment by qingqing01** [comment]
Hi, @huangpingchun please note the ResNet model document: http://www.paddlepaddle.org/doc/demo/imagenet_model/resnet_model.html

"Note, since the convolution layer in these ResNet models is suitable for the cudnn implementation which only support GPU. It not support CPU mode because of compatibility issue and we will fix later."

So please use GPU to test.

**Comment by huangpingchun** [comment]
ok, thank you, I recently noticed mxnet pre-training model resnet must also be run on the GPU down.
