### ISSUE TITLE
support config different port for different trainer in cluster mode

### ISSUE THREAD

**Issue by jacquesqiao** [baidu/Paddle#435]
now the configuration for distributed paddle is:
```
 --pservers=host1,host2 --port=1234
```
It have some problems:
1.  we can only start one trainer on one machine because all trainer share the same port for communication. 
2. If the port on one of all the machines is used by other program, the whole job will fail.

Can we modify it to the format like tensorflow, for example:
```
--cluster_spec='worker|host1:port1,ps|host2:port2'
```
so that we can start multi trainer on one machine.

**Comment by backyes** [comment]
For cluster job，if multiple trainers share single node，the overall performance could decrease since different trainers could idle-waits each other if sync-sgd was used.



-------- 原始邮件 --------
发件人：jacquesqiao <notifications@github.com>
时间：周五 11月11日 16:10
收件人：baidu/Paddle <Paddle@noreply.github.com>
主题：[baidu/Paddle] support config different port for different trainer in cluster mode (#435)


now the configuration for distributed paddle is:

 --pservers=host1,host2 --port=1234


It have some problems:

  1.  we can only start one trainer on one machine because all trainer share the same port for communication.
  2.  If the port on one of all the machines is used by other program, the whole job will fail.

Can we modify it to the format like tensorflow, for example:

--cluster_spec='worker|host1:port1,ps|host2:port2'


so that we can start multi trainer on one machine.

**Comment by backyes** [comment]
no response for long time, so close it
