### ISSUE TITLE
Question about the learning rate assignment

### ISSUE THREAD

**Issue by CrossLee1** [baidu/Paddle#518]
In the demo of sentiment, I see the stack lstm is used for this classification task ([this file](https://github.com/baidu/Paddle/blob/develop/demo/sentiment/sentiment_net.py#L78)).

I have some questions about the learning rate. 
In line [105](https://github.com/baidu/Paddle/blob/develop/demo/sentiment/sentiment_net.py#L105), the `para_attr` is a list, which contains the learning rate of fc_layer and lstm_layer. 
In line [123](https://github.com/baidu/Paddle/blob/develop/demo/sentiment/sentiment_net.py#L123), the fc_layer uses the `param_attr` to get the learning rate, but the following lstm does not have a `param_attr`.
Then could the second element of the `para_attr` be conveyed to lstm? How?

**Comment by qingqing01** [comment]
Hi, @CrossLee1
The lines from [103](https://github.com/baidu/Paddle/blob/develop/demo/sentiment/sentiment_net.py#L103) to [105](https://github.com/baidu/Paddle/blob/develop/demo/sentiment/sentiment_net.py#L105) sets parameter more  precisely. Actually, it is ok without these settings.

```
    inputs = [fc1, lstm1]
    for i in range(2, stacked_num + 1):
        fc = fc_layer(
            input=inputs,
            size=hid_dim,
            act=linear,
            param_attr=para_attr,
            bias_attr=bias_attr)
        lstm = lstmemory(
            input=fc,
            reverse=(i % 2) == 0,
            act=relu,
            bias_attr=bias_attr,
            layer_attr=layer_attr)
        inputs = [fc, lstm]
```

Because the [inputs](https://github.com/baidu/Paddle/blob/develop/demo/sentiment/sentiment_net.py#L120) of `fc_layer` contains two layers. That is to say the input is a list of `[fc_layer,  lstm]`.
The list of `para_attr` is used to set parameter attribute of each input layer. That is to say `para_attr[0] ` is the parameter attribute of the first input `fc_layer`, the `para_attr[1]` is the parameter attribute of the second input `lstm`. 

If you want to know the details, you can see code of `fc_layer`.
https://github.com/baidu/Paddle/blob/develop/python/paddle/trainer_config_helpers/layers.py#L876

**Comment by CrossLee1** [comment]
@qingqing01 
I see. Thanks for your detailed explanation.

Closed#
