### ISSUE TITLE
Parallelized version of CpuVectorT<real>::uniform and similar functions

### ISSUE THREAD

**Issue by byzhang** [baidu/Paddle#77]
I can think of OpenMP, but not sure whether it fits your threading model. If you can point me some reference code, I'm happy to create a pull request.

**Comment by reyoung** [comment]
Well, the uniform & randnorm method, will be moved from C++ part of PaddlePaddle to Python part in our plan. Because we want to support more flexible parameter initialization strategies. Only the `zeroMem` method  will be remained later.

And currently ParallelCpuVectorT is a parallelized version and use multiple threads explicitly by `paddle::SyncThreadPool`.  The OpenMP is cool but need an extra dependency. We may not want to use it now.

Thanks for your attention.

**Comment by byzhang** [comment]
Thank you for the information. Can you please keep existing functions?
Protobuf message has 2G limits which means sometimes we cannot init all
parameters in Python and pass to Paddle in a proto.

**Comment by reyoung** [comment]
@byzhang O....Maybe we will write the parameter file into output files.

**Comment by byzhang** [comment]
My two cents, keep the python layer as simple as possible, as thin as
possible :)

Thanks,
-B
